<?php
declare(strict_types=1);
namespace Biblio\Core\Application\Assessments;
use Biblio\Core\Application\Identity\AuthenticatedUser; use Biblio\Core\Application\Library\LibraryAccessService; use Biblio\Core\Application\TransactionManager;
use Biblio\Core\Assessments\{AssessmentClock,AssessmentIdCollisionExhausted,ContributionPublication,ModerationReason,ModerationStatus,PublicationId,PublicationIdCollision,PublicationIdGenerator,PublicationIneligible,PublicationNotAvailable,PublicationStale,PublicationVersion,RatingId,ReviewId,WritablePublicationRepository,WritableRatingRepository,WritableReviewRepository};
use Biblio\Core\Catalog\{LibraryWorkRepresentationRepository,WorkId}; use Biblio\Core\Library\{LibraryContext,LibraryId,LibraryMutationLock};
final readonly class PublicationService
{
    public function __construct(private AuthenticatedUser $auth,private LibraryAccessService $access,private LibraryMutationLock $locks,private LibraryWorkRepresentationRepository $represented,private WritableRatingRepository $ratings,private WritableReviewRepository $reviews,private WritablePublicationRepository $publications,private PublicationIdGenerator $ids,private AssessmentClock $clock,private TransactionManager $tx){}
    public function publishRating(RatingId $id,LibraryId $library):ContributionPublication{$actor=$this->auth->requireUserId();return $this->tx->run(function()use($actor,$id,$library):ContributionPublication{$this->eligible($library,$actor);$source=$this->ratings->findForUserForUpdate($id,$actor);if($source===null)throw new PublicationNotAvailable();$this->presence($library,$source->workId());$history=$this->publications->findRatingHistory($id,$library);if($history!==null){if($history->authorStatus()===\Biblio\Core\Assessments\AuthorStatus::Active)return $history;$next=$history->republish($this->clock->now());if(!$this->publications->replaceIfVersionMatches($next,$history->version()))throw new PublicationStale();return $next;}return $this->addWithRetry(fn(PublicationId $publicationId):ContributionPublication=>ContributionPublication::forRating($publicationId,$library,$id,$this->clock->now()));});}
    public function publishReview(ReviewId $id,LibraryId $library):ContributionPublication{$actor=$this->auth->requireUserId();return $this->tx->run(function()use($actor,$id,$library):ContributionPublication{$this->eligible($library,$actor);$source=$this->reviews->findForUserForUpdate($id,$actor);if($source===null)throw new PublicationNotAvailable();$this->presence($library,$source->workId());$history=$this->publications->findReviewHistory($id,$library);if($history!==null){if($history->authorStatus()===\Biblio\Core\Assessments\AuthorStatus::Active)return $history;$next=$history->republish($this->clock->now());if(!$this->publications->replaceIfVersionMatches($next,$history->version()))throw new PublicationStale();return $next;}return $this->addWithRetry(fn(PublicationId $publicationId):ContributionPublication=>ContributionPublication::forReview($publicationId,$library,$id,$this->clock->now()));});}
    public function withdraw(PublicationId $id,PublicationVersion $expected):ContributionPublication{$actor=$this->auth->requireUserId();return $this->tx->run(function()use($actor,$id,$expected):ContributionPublication{$p=$this->publications->findForOwnerForUpdate($id,$actor);if($p===null)throw new PublicationNotAvailable();if($p->authorStatus()===\Biblio\Core\Assessments\AuthorStatus::Withdrawn)return $p;if(!$p->version()->equals($expected))throw new PublicationStale();$next=$p->withdraw($this->clock->now());if(!$this->publications->replaceIfVersionMatches($next,$expected))throw new PublicationStale();return $next;});}
    public function move(PublicationId $id,PublicationVersion $expected,LibraryId $target):ContributionPublication{$actor=$this->auth->requireUserId();return $this->tx->run(function()use($actor,$id,$expected,$target):ContributionPublication{$current=$this->publications->findForOwnerForUpdate($id,$actor);if($current===null||!$current->version()->equals($expected))throw new PublicationStale();$this->eligible($target,$actor);$work=$this->sourceWork($current,$actor);$this->presence($target,$work);$withdrawn=$current->withdraw($this->clock->now());if(!$this->publications->replaceIfVersionMatches($withdrawn,$expected))throw new PublicationStale();if($current->ratingId()!==null)return $this->publishMovedRating($current->ratingId(),$target);return $this->publishMovedReview($current->reviewId(),$target);});}
    public function moderate(PublicationId $id,LibraryId $library,PublicationVersion $expected,ModerationStatus $status,ModerationReason $reason):ContributionPublication{$actor=$this->auth->requireUserId();return $this->tx->run(function()use($actor,$id,$library,$expected,$status,$reason):ContributionPublication{$this->locks->acquire($library);if(!$this->access->canModerateContribution(new LibraryContext($library,$actor)))throw new PublicationIneligible();$p=$this->publications->findInLibraryForUpdate($id,$library);if($p===null)throw new PublicationNotAvailable();if(!$p->version()->equals($expected))throw new PublicationStale();$next=$p->moderate($status,$reason,$actor,$this->clock->now());if(!$this->publications->replaceIfVersionMatches($next,$expected))throw new PublicationStale();return $next;});}
    public function restore(PublicationId $id,LibraryId $library,PublicationVersion $expected):ContributionPublication{$actor=$this->auth->requireUserId();return $this->tx->run(function()use($actor,$id,$library,$expected):ContributionPublication{$this->locks->acquire($library);if(!$this->access->canModerateContribution(new LibraryContext($library,$actor)))throw new PublicationIneligible();$p=$this->publications->findInLibraryForUpdate($id,$library);if($p===null)throw new PublicationNotAvailable();if(!$p->version()->equals($expected))throw new PublicationStale();$next=$p->restore($this->clock->now());if(!$this->publications->replaceIfVersionMatches($next,$expected))throw new PublicationStale();return $next;});}
    private function eligible(LibraryId $library,\Biblio\Core\Identity\UserId $actor):void{$this->locks->acquire($library);if(!$this->access->canPublishContribution(new LibraryContext($library,$actor)))throw new PublicationIneligible();}
    private function presence(LibraryId $library,WorkId $work):void{if(!$this->represented->hasActiveWorkRepresentation($library,$work))throw new PublicationIneligible();}
    private function sourceWork(ContributionPublication $p,\Biblio\Core\Identity\UserId $actor):WorkId{if($p->ratingId()!==null){$s=$this->ratings->findForUserForUpdate($p->ratingId(),$actor);if($s===null)throw new PublicationNotAvailable();return $s->workId();}$id=$p->reviewId();if($id===null)throw new PublicationNotAvailable();$s=$this->reviews->findForUserForUpdate($id,$actor);if($s===null)throw new PublicationNotAvailable();return $s->workId();}
    private function publishMovedRating(RatingId $id,LibraryId $target):ContributionPublication{$history=$this->publications->findRatingHistory($id,$target);if($history!==null){$next=$history->republish($this->clock->now());if(!$this->publications->replaceIfVersionMatches($next,$history->version()))throw new PublicationStale();return $next;}return $this->addWithRetry(fn(PublicationId $publicationId):ContributionPublication=>ContributionPublication::forRating($publicationId,$target,$id,$this->clock->now()));}
    private function publishMovedReview(?ReviewId $id,LibraryId $target):ContributionPublication{if($id===null)throw new PublicationNotAvailable();$history=$this->publications->findReviewHistory($id,$target);if($history!==null){$next=$history->republish($this->clock->now());if(!$this->publications->replaceIfVersionMatches($next,$history->version()))throw new PublicationStale();return $next;}return $this->addWithRetry(fn(PublicationId $publicationId):ContributionPublication=>ContributionPublication::forReview($publicationId,$target,$id,$this->clock->now()));}
    /** @param callable(PublicationId): ContributionPublication $factory */ private function addWithRetry(callable $factory):ContributionPublication{$attempt=0;while(true){$publication=$factory($this->ids->next());try{$this->publications->add($publication);return $publication;}catch(PublicationIdCollision $collision){if($attempt++>=3)throw new AssessmentIdCollisionExhausted($collision);}}}
}
