<?php
declare(strict_types=1);
namespace Biblio\Core\Application\Assessments;
use Biblio\Core\Application\Identity\AuthenticatedUser; use Biblio\Core\Application\TransactionManager;
use Biblio\Core\Assessments\{AssessmentClock,AssessmentIdCollisionExhausted,AssessmentStale,Rating,RatingId,RatingIdCollision,RatingIdGenerator,RatingNotAvailable,RatingValue,RatingVersion,ReviewContent,ReviewId,ReviewIdCollision,ReviewIdGenerator,ReviewNotAvailable,ReviewVersion,WritableRatingRepository,WritableReviewRepository,WrittenReview};
use Biblio\Core\Catalog\{WorkId,WorkRepository}; use Biblio\Core\Exception\ValidationException; use Biblio\Core\Reading\{ReadingRoundId,ReadingRoundRepository};
final readonly class SourceContributionService
{
    public function __construct(private AuthenticatedUser $auth,private WorkRepository $works,private ReadingRoundRepository $rounds,private WritableRatingRepository $ratings,private WritableReviewRepository $reviews,private RatingIdGenerator $ratingIds,private ReviewIdGenerator $reviewIds,private AssessmentClock $clock,private TransactionManager $tx){}
    public function createRatingForWork(WorkId $work,RatingValue $value):Rating{$actor=$this->auth->requireUserId();return $this->tx->run(function()use($actor,$work,$value):Rating{if($this->works->find($work)===null)throw new ValidationException('Work does not exist.');return $this->createRating($actor,$work,null,$value);});}
    public function createRatingForRound(ReadingRoundId $round,RatingValue $value):Rating{$actor=$this->auth->requireUserId();return $this->tx->run(function()use($actor,$round,$value):Rating{$rr=$this->rounds->findForUserForUpdate($round,$actor);if($rr===null)throw new RatingNotAvailable();return $this->createRating($actor,$rr->workId(),$rr->id(),$value);});}
    public function createReviewForWork(WorkId $work,ReviewContent $content):WrittenReview{$actor=$this->auth->requireUserId();return $this->tx->run(function()use($actor,$work,$content):WrittenReview{if($this->works->find($work)===null)throw new ValidationException('Work does not exist.');return $this->createReview($actor,$work,null,$content);});}
    public function createReviewForRound(ReadingRoundId $round,ReviewContent $content):WrittenReview{$actor=$this->auth->requireUserId();return $this->tx->run(function()use($actor,$round,$content):WrittenReview{$rr=$this->rounds->findForUserForUpdate($round,$actor);if($rr===null)throw new ReviewNotAvailable();return $this->createReview($actor,$rr->workId(),$rr->id(),$content);});}
    public function updateRating(RatingId $id,RatingVersion $expected,RatingValue $value):Rating{$actor=$this->auth->requireUserId();return $this->tx->run(function()use($actor,$id,$expected,$value):Rating{$current=$this->ratings->findForUserForUpdate($id,$actor);if($current===null)throw new RatingNotAvailable();if($current->value()->equals($value))return $current;if(!$current->version()->equals($expected))throw new AssessmentStale();$next=$current->withValue($value,$this->clock->now());if(!$this->ratings->replaceIfVersionMatches($actor,$next,$expected))throw new AssessmentStale();return $next;});}
    public function updateReview(ReviewId $id,ReviewVersion $expected,ReviewContent $content):WrittenReview{$actor=$this->auth->requireUserId();return $this->tx->run(function()use($actor,$id,$expected,$content):WrittenReview{$current=$this->reviews->findForUserForUpdate($id,$actor);if($current===null)throw new ReviewNotAvailable();if($current->content()->equals($content))return $current;if(!$current->version()->equals($expected))throw new AssessmentStale();$next=$current->withContent($content,$this->clock->now());if(!$this->reviews->replaceIfVersionMatches($actor,$next,$expected))throw new AssessmentStale();return $next;});}
    public function correctRatingRound(RatingId $id,RatingVersion $expected,?ReadingRoundId $round):Rating{$actor=$this->auth->requireUserId();return $this->tx->run(function()use($actor,$id,$expected,$round):Rating{$current=$this->ratings->findForUserForUpdate($id,$actor);if($current===null)throw new RatingNotAvailable();if($current->hasRound($round))return $current;if(!$current->version()->equals($expected))throw new AssessmentStale();$this->assertRound($round,$actor,$current->workId(),true);$next=$current->withReadingRound($round,$this->clock->now());if(!$this->ratings->replaceIfVersionMatches($actor,$next,$expected))throw new AssessmentStale();return $next;});}
    public function correctReviewRound(ReviewId $id,ReviewVersion $expected,?ReadingRoundId $round):WrittenReview{$actor=$this->auth->requireUserId();return $this->tx->run(function()use($actor,$id,$expected,$round):WrittenReview{$current=$this->reviews->findForUserForUpdate($id,$actor);if($current===null)throw new ReviewNotAvailable();if($current->hasRound($round))return $current;if(!$current->version()->equals($expected))throw new AssessmentStale();$this->assertRound($round,$actor,$current->workId(),false);$next=$current->withReadingRound($round,$this->clock->now());if(!$this->reviews->replaceIfVersionMatches($actor,$next,$expected))throw new AssessmentStale();return $next;});}
    public function deleteRating(RatingId $id,RatingVersion $expected):void{$actor=$this->auth->requireUserId();$this->tx->run(function()use($actor,$id,$expected):void{$current=$this->ratings->findForUserForUpdate($id,$actor);if($current===null)throw new RatingNotAvailable();if(!$current->version()->equals($expected)||!$this->ratings->deleteIfVersionMatches($actor,$id,$expected))throw new AssessmentStale();});}
    public function deleteReview(ReviewId $id,ReviewVersion $expected):void{$actor=$this->auth->requireUserId();$this->tx->run(function()use($actor,$id,$expected):void{$current=$this->reviews->findForUserForUpdate($id,$actor);if($current===null)throw new ReviewNotAvailable();if(!$current->version()->equals($expected)||!$this->reviews->deleteIfVersionMatches($actor,$id,$expected))throw new AssessmentStale();});}
    private function assertRound(?ReadingRoundId $id,\Biblio\Core\Identity\UserId $actor,WorkId $work,bool $rating):void{if($id===null)return;$round=$this->rounds->findForUserForUpdate($id,$actor);if($round===null||!$round->workId()->equals($work)){if($rating)throw new RatingNotAvailable();throw new ReviewNotAvailable();}}
    private function createRating(\Biblio\Core\Identity\UserId $actor,WorkId $work,?ReadingRoundId $round,RatingValue $value):Rating{$attempt=0;while(true){$rating=Rating::create($this->ratingIds->next(),$actor,$work,$round,$value,$this->clock->now());try{$this->ratings->addForUser($actor,$rating);return $rating;}catch(RatingIdCollision $collision){if($attempt++>=3)throw new AssessmentIdCollisionExhausted($collision);}}}
    private function createReview(\Biblio\Core\Identity\UserId $actor,WorkId $work,?ReadingRoundId $round,ReviewContent $content):WrittenReview{$attempt=0;while(true){$review=WrittenReview::create($this->reviewIds->next(),$actor,$work,$round,$content,$this->clock->now());try{$this->reviews->addForUser($actor,$review);return $review;}catch(ReviewIdCollision $collision){if($attempt++>=3)throw new AssessmentIdCollisionExhausted($collision);}}}
}
