import { expect, test } from "@playwright/test";

const login = async page => {
    await page.goto("/wp-login.php");
    await expect(page.locator("#user_login")).toBeFocused();
    await page.locator("#user_login").fill("biblio_entry_e2e_owner");
    await page.locator("#user_pass").fill(process.env.BIBLIO_E2E_ACTOR_PASSWORD);
    await page.locator("#wp-submit").click();
    await page.getByRole("textbox", {name:"Bibliotheeknaam",exact:true}).fill("Instellingen testbibliotheek");
    await page.getByRole("button", {name:"Opslaan en verder"}).click();
    await expect(page).toHaveURL(/\/mijn-biblio\/$/);
    await expect(page.getByRole("link",{name:/Mijn voorkeuren voor/})).toHaveCount(0);
    await page.getByRole("link", {name:"Instellingen testbibliotheek",exact:true}).click();
    const id = new URL(page.url()).searchParams.get("library_id");
    await page.getByRole("link", {name:"Mijn voorkeuren voor Instellingen testbibliotheek",exact:true}).click();
    await expect(page).toHaveURL(new RegExp(`/instellingen/\\?library_id=${id}`));
    await expect(page.getByRole("heading",{name:"Mijn voorkeuren",exact:true})).toBeVisible();
    return id;
};
const controls = page => ({ mine:page.locator("fieldset").nth(0), archive:page.locator("fieldset").nth(1) });

test("scoped settings, immediate saves, inherited defaults, reset, mobile and independent tabs", async ({page,context}) => {
    const errors=[]; page.on("pageerror", error=>errors.push(error.message));
    const personalRequests=[];
    page.on('request',request=>personalRequests.push(request.url()));
    const id = await login(page);
    expect(personalRequests.some(url=>url.endsWith('/defaults'))).toBe(false);
    const {mine,archive} = controls(page);
    await expect(page.locator("fieldset")).toHaveCount(2);
    const management = await context.newPage();
    const requests=[];
    management.on('request',request=>requests.push(request.url()));
    await management.goto(`/bibliotheekinstellingen/?library_id=${id}`);
    await expect(management.getByRole('heading',{name:'Bibliotheekinstellingen',exact:true})).toBeVisible();
    await expect(management.locator('fieldset')).toHaveCount(1);
    expect(requests.some(url=>url.endsWith('/preferences'))).toBe(false);
    const shared=management.locator('fieldset');
    await management.screenshot({path:"project/bewijs/V2001-SETTINGS-10-beheer-desktop.png",fullPage:true,animations:"disabled"});
    await expect(mine.getByRole("radio",{name:"Biblio-standaard gebruiken (Kaarten)",exact:true})).toBeChecked();
    await page.screenshot({path:"project/bewijs/V2001-SETTINGS-10-desktop.png",fullPage:true,animations:"disabled"});
    await page.getByRole('button',{name:'Navigatie inklappen',exact:true}).click();
    const mineLink=page.getByRole('link',{name:'Mijn voorkeuren voor Instellingen testbibliotheek'});
    const manageLink=page.getByRole('link',{name:'Bibliotheekinstellingen voor Instellingen testbibliotheek'});
    await mineLink.focus(); await expect(mineLink).toBeFocused();
    await manageLink.focus(); await expect(manageLink).toBeFocused();
    await page.keyboard.press('Enter');
    await expect(page.getByRole('heading',{name:'Bibliotheekinstellingen',exact:true})).toBeVisible();
    await expect(page.locator('fieldset')).toHaveCount(1);
    await page.screenshot({path:'project/bewijs/V2001-SETTINGS-10-beheer-rail.png',fullPage:true,animations:"disabled"});
    await page.getByRole('link',{name:'Mijn voorkeuren voor Instellingen testbibliotheek'}).focus();
    await page.keyboard.press('Enter');
    await expect(page.getByRole('heading',{name:'Mijn voorkeuren',exact:true})).toBeVisible();
    await page.getByRole('button',{name:'Navigatie uitklappen',exact:true}).click();
    await shared.getByRole("radio",{name:"Lijst",exact:true}).check();
    await expect(shared.getByRole("status")).toHaveText("Opgeslagen");
    await page.reload();
    await expect(mine.getByText("Laatst bevestigd: Lijst · Bibliotheekstandaard")).toBeVisible();
    await mine.getByRole("radio",{name:"Kaarten",exact:true}).check();
    await expect(mine.getByRole("status")).toHaveText("Opgeslagen");
    await expect(mine.getByText("Laatst bevestigd: Kaarten · Eigen keuze")).toBeVisible();
    await archive.getByRole("switch",{name:"Archief tonen"}).check();
    await expect(archive.getByRole("status")).toHaveText("Opgeslagen");
    await page.setViewportSize({width:400,height:756});
    expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
    await expect(page.getByRole("link",{name:"Mijn voorkeuren voor Instellingen testbibliotheek"})).toBeHidden();
    await page.screenshot({path:"project/bewijs/V2001-SETTINGS-10-mobiel.png",fullPage:true,animations:"disabled"});
    await page.getByRole("button",{name:"Navigatie openen"}).click();
    await expect(page.getByRole("link",{name:"Mijn voorkeuren voor Instellingen testbibliotheek"})).toBeVisible();
    await expect(page.getByRole('link',{name:'Bibliotheekinstellingen voor Instellingen testbibliotheek'})).toBeVisible();
    await page.keyboard.press("Escape");
    await management.setViewportSize({width:400,height:756});
    expect(await management.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
    await expect(management.locator('[data-mobile-nav-open]')).toHaveAttribute('data-mobile-nav-open','false');
    await management.screenshot({path:"project/bewijs/V2001-SETTINGS-10-beheer-mobiel.png",fullPage:true,animations:"disabled"});
    await management.getByRole('button',{name:'Navigatie openen'}).click();
    await management.screenshot({path:'project/bewijs/V2001-SETTINGS-10-beheer-mobiele-navigatie.png',fullPage:true,animations:"disabled"});
    await management.getByRole('link',{name:'Mijn voorkeuren voor Instellingen testbibliotheek'}).click();
    await expect(management.getByRole('heading',{name:'Mijn voorkeuren',exact:true})).toBeVisible();
    await management.goto(`/bibliotheekinstellingen/?library_id=${id}`);
    await expect(management.locator('fieldset')).toHaveCount(1);
    // Server denial after initial load clears both controls and Library navigation.
    await management.route('**/wp-json/biblio/v1/libraries/*/defaults',route=>route.fulfill({status:404,contentType:'application/json',body:JSON.stringify({code:'not_found',message:'Niet beschikbaar',data:{status:404}})}));
    await management.locator('fieldset').getByRole('radio',{name:'Kaarten',exact:true}).check();
    await expect(management.getByText('Je aanmelding of bibliotheektoegang is gewijzigd. Open de bibliotheek opnieuw.')).toBeVisible();
    await expect(management.locator('fieldset')).toHaveCount(0);
    await expect(management.getByRole('link',{name:/Bibliotheekinstellingen voor/})).toHaveCount(0);
    await management.close();
    const tab = await context.newPage();
    await tab.goto(`/mijn-bibliotheek/?library_id=${id}`);
    await expect(tab.getByRole("button",{name:"Grid",exact:true})).toHaveAttribute("aria-pressed","true");
    await tab.getByRole("button",{name:"Lijst",exact:true}).click();
    await mine.getByRole("radio",{name:"Bibliotheekstandaard gebruiken (Lijst)",exact:true}).check();
    await expect(mine.getByRole("status")).toHaveText("Opgeslagen");
    await tab.reload();
    await expect(tab.getByRole("button",{name:"Lijst",exact:true})).toHaveAttribute("aria-pressed","true");
    await tab.getByRole("button",{name:"Grid",exact:true}).click();
    await mine.getByRole("radio",{name:"Lijst",exact:true}).check();
    await expect(mine.getByRole("status")).toHaveText("Opgeslagen");
    await tab.reload();
    await expect(tab.getByRole("button",{name:"Lijst",exact:true})).toHaveAttribute("aria-pressed","true");
    await archive.getByRole("button",{name:"Biblio-standaard gebruiken"}).click();
    await expect(archive.getByRole("status")).toHaveText("Opgeslagen");
    await expect(archive.getByRole("switch")).not.toBeChecked();
    await expect(archive.getByRole("button",{name:"Biblio-standaard gebruiken"})).toBeHidden();
    // Native switch keyboard operation, including explicit own-off and reset.
    await archive.getByRole("switch").focus();
    await page.keyboard.press("Space");
    await expect(archive.getByRole("status")).toHaveText("Opgeslagen");
    await expect(archive.getByRole("switch")).toBeChecked();
    await page.keyboard.press("Space");
    await expect(archive.getByRole("status")).toHaveText("Opgeslagen");
    await expect(archive.getByText("Laatst bevestigd: Uit · Eigen keuze")).toBeVisible();
    await archive.getByRole("button",{name:"Biblio-standaard gebruiken"}).click();
    await expect(archive.getByText("Laatst bevestigd: Uit · Biblio-standaard")).toBeVisible();
    await page.reload(); await expect(mine.getByRole("radio",{name:"Lijst",exact:true})).toBeChecked();
    await page.setViewportSize({width:1280,height:900});
    await page.getByRole("link",{name:"Mijn Biblio",exact:true}).click();
    await expect(page.getByRole("link",{name:/Mijn voorkeuren voor/})).toHaveCount(0);
    await expect(page.getByRole('link',{name:/Bibliotheekinstellingen voor/})).toHaveCount(0);
    await tab.close(); expect(errors).toEqual([]);

    await page.goto(`/instellingen/?library_id=${id}`);
    let loseResponse=true; let patches=0;
    await page.route('**/wp-json/biblio/v1/libraries/*/preferences',async route=>{
        if (route.request().method()!=='PATCH') return route.continue();
        patches++;
        if (loseResponse) {loseResponse=false; await route.fetch(); return route.abort('failed');}
        return route.continue();
    });
    await mine.getByRole('radio',{name:'Kaarten',exact:true}).check();
    await expect(mine.getByRole('status')).toContainText('Opslag niet bevestigd');
    await expect(archive.getByRole('switch')).toBeEnabled();
    await mine.getByRole('button',{name:'Opnieuw proberen'}).click();
    await expect(mine.getByRole('status')).toHaveText('Opgeslagen');
    expect(patches).toBe(1);
    // Another tab saves after this tab read its version.
    const peer=await page.context().newPage(); await peer.goto(`/instellingen/?library_id=${id}`);
    await controls(peer).mine.getByRole('radio',{name:'Lijst',exact:true}).check();
    await expect(controls(peer).mine.getByRole('status')).toHaveText('Opgeslagen');
    await mine.getByRole('radio',{name:'Bibliotheekstandaard gebruiken (Lijst)',exact:true}).check();
    await expect(mine.getByRole('status')).toContainText('intussen gewijzigd');
    await mine.getByRole('button',{name:'Actuele waarde ophalen'}).click();
    await expect(mine.getByRole('radio',{name:'Lijst',exact:true})).toBeChecked();
    await peer.close(); await page.unroute('**/wp-json/biblio/v1/libraries/*/preferences');
    await page.goto('/instellingen/'); await expect(page.getByText('Open Instellingen vanuit een specifieke bibliotheek.')).toBeVisible();
    await page.goto('/instellingen/?library_id=missing'); await expect(page.locator('fieldset')).toHaveCount(0);
    await page.getByRole('link',{name:'Uitloggen',exact:true}).click();
    await page.goto(`/instellingen/?library_id=${id}`);
    await expect(page.getByText('Log in om je voorkeuren te bekijken.')).toBeVisible();
    await expect(page.locator('fieldset')).toHaveCount(0);
    const loginHref=await page.getByRole('link',{name:'Inloggen',exact:true}).last().getAttribute('href');
    expect(new URL(loginHref).searchParams.get('redirect_to')).toContain(`/instellingen/?library_id=${id}`);
    await page.goto(`/bibliotheekinstellingen/?library_id=${id}`);
    await expect(page.getByText('Log in om de Bibliotheekinstellingen te bekijken.')).toBeVisible();
    await expect(page.locator('fieldset')).toHaveCount(0);
    const manageLoginHref=await page.getByRole('link',{name:'Inloggen',exact:true}).last().getAttribute('href');
    expect(new URL(manageLoginHref).searchParams.get('redirect_to')).toContain(`/bibliotheekinstellingen/?library_id=${id}`);
    // A different authenticated account cannot access this Library's management.
    await page.goto('/wp-login.php');
    await page.locator('#user_login').fill('biblio_entry_e2e_other');
    await page.locator('#user_pass').fill(process.env.BIBLIO_E2E_ACTOR_PASSWORD);
    await page.locator('#wp-submit').click();
    await page.getByRole('textbox',{name:'Bibliotheeknaam',exact:true}).fill('Andere testbibliotheek');
    await page.getByRole('button',{name:'Opslaan en verder'}).click();
    await page.goto(`/bibliotheekinstellingen/?library_id=${id}`);
    await expect(page.getByText('Instellingen konden niet worden geladen.')).toBeVisible();
    await expect(page.locator('fieldset')).toHaveCount(0);
    await expect(page.getByRole('link',{name:/Bibliotheekinstellingen voor/})).toHaveCount(0);
    expect(errors).toEqual([]);
});
