<?php
declare(strict_types=1);
namespace Biblio\Core\Tests\Integration;
use Biblio\Core\Application\Assessments\SourceContributionService;use Biblio\Core\Assessments\{AssessmentIdCollisionExhausted,RatingId,RatingIdGenerator,RatingValue,ReviewContent,ReviewId,ReviewIdGenerator};use Biblio\Core\Catalog\WorkId;use Biblio\Core\Infrastructure\Persistence\WordPress\{WpdbRatingRepository,WpdbReadingRoundRepository,WpdbReviewRepository,WpdbTransactionManager,WpdbWorkRepository};use Biblio\Core\Infrastructure\WordPress\Identity\WordPressAuthenticatedUser;use Biblio\Core\Infrastructure\WordPress\SystemAssessmentClock;
final class AssessmentIdRetryTest extends PersistenceIntegrationTestCase
{
    /** @var list<int> */ private array $users=[];
    protected function tearDown():void{wp_set_current_user(0);foreach($this->users as $id){$this->database->delete($this->database->usermeta,['user_id'=>$id]);$this->database->delete($this->database->users,['ID'=>$id]);}parent::tearDown();}
    public function testRatingAndReviewPrimaryKeyCollisionRetryAndExhaustion():void{$suffix=bin2hex(random_bytes(4));$author=wp_insert_user(['user_login'=>'retry-author-'.$suffix,'user_pass'=>'secret']);$other=wp_insert_user(['user_login'=>'retry-other-'.$suffix,'user_pass'=>'secret']);self::assertIsInt($author);self::assertIsInt($other);$this->users=[(int)$author,(int)$other];wp_set_current_user((int)$author);foreach([['application-work','Application'],['collision-work','Collision']] as [$id,$title])$this->database->insert($this->tableNames->works(),['work_id'=>$id,'work_title'=>$title]);$this->database->insert($this->tableNames->ratings(),['rating_id'=>'rating-collision','user_id'=>(string)$other,'work_id'=>'collision-work','reading_round_id'=>null,'rating_half_units'=>6,'created_at'=>'2026-08-23 10:00:00.000000','updated_at'=>'2026-08-23 10:00:00.000000','rating_version'=>1]);$this->database->insert($this->tableNames->reviews(),['review_id'=>'review-collision','user_id'=>(string)$other,'work_id'=>'collision-work','reading_round_id'=>null,'review_content'=>'existing','created_at'=>'2026-08-23 10:00:00.000000','updated_at'=>'2026-08-23 10:00:00.000000','review_version'=>1]);$source=$this->source(new SequenceRatingIds('rating-collision','rating-after-collision'),new SequenceReviewIds('review-collision','review-after-collision'));self::assertSame('rating-after-collision',$source->createRatingForWork(new WorkId('application-work'),RatingValue::fromStars(3))->id()->value());self::assertSame('review-after-collision',$source->createReviewForWork(new WorkId('application-work'),ReviewContent::fromString('new'))->id()->value());$exhausted=$this->source(new SequenceRatingIds('rating-collision','rating-collision','rating-collision','rating-collision'),new SequenceReviewIds('unused-review'));$this->expectException(AssessmentIdCollisionExhausted::class);$exhausted->createRatingForWork(new WorkId('collision-work'),RatingValue::fromStars(4));}
    private function source(RatingIdGenerator $ratingIds,ReviewIdGenerator $reviewIds):SourceContributionService{$ratings=new WpdbRatingRepository($this->database,$this->tableNames);return new SourceContributionService(new WordPressAuthenticatedUser(),new WpdbWorkRepository($this->database,$this->tableNames),new WpdbReadingRoundRepository($this->database,$this->tableNames),$ratings,new WpdbReviewRepository($this->database,$this->tableNames),$ratingIds,$reviewIds,new SystemAssessmentClock(),new WpdbTransactionManager($this->database));}
}
final class SequenceRatingIds implements RatingIdGenerator{private int $index=0;/** @var list<string> */private array $ids;public function __construct(string ...$ids){$this->ids=$ids;}public function next():RatingId{return new RatingId($this->ids[$this->index++]);}}
final class SequenceReviewIds implements ReviewIdGenerator{private int $index=0;/** @var list<string> */private array $ids;public function __construct(string ...$ids){$this->ids=$ids;}public function next():ReviewId{return new ReviewId($this->ids[$this->index++]);}}
