<?php
declare(strict_types=1);
namespace Biblio\Core\Tests\Integration;
use Biblio\Core\Assessments\{ContributionPublication,ModerationReason,ModerationStatus,PublicationId,Rating,RatingId,RatingValue,ReviewContent,ReviewId,WrittenReview};use Biblio\Core\Catalog\WorkId;use Biblio\Core\Identity\UserId;use Biblio\Core\Infrastructure\Persistence\WordPress\{WpdbPublicationRepository,WpdbRatingRepository,WpdbReviewRepository,WpdbTransactionConnection,WpdbTransactionManager};use Biblio\Core\Library\LibraryId;use Biblio\Core\Reading\ReadingRoundId;use DateTimeImmutable;
final class RatingsReviewsProjectionTest extends PersistenceIntegrationTestCase
{
    /** @var list<int> */ private array $createdUsers=[];
    protected function tearDown():void{foreach($this->createdUsers as $id){$this->database->delete($this->database->usermeta,['user_id'=>$id]);$this->database->delete($this->database->users,['ID'=>$id]);}parent::tearDown();}
    public function testPublicProjectionDeduplicatesAndTracksVisibilityAndActivePresence():void
    {
        [$userA,$userB]=$this->createUsers();$this->seedLibraryWork($userA);$tx=new WpdbTransactionManager(new WpdbTransactionConnection($this->database));$ratings=new WpdbRatingRepository($this->database,$this->tableNames);$reviews=new WpdbReviewRepository($this->database,$this->tableNames);$publications=new WpdbPublicationRepository($this->database,$this->tableNames);$work=new WorkId('projection-work');$library=new LibraryId('projection-library');$t=new DateTimeImmutable('2026-08-22T10:00:00.000000+00:00');
        $rOld=Rating::create(new RatingId('rating-a-old'),$userA,$work,null,RatingValue::fromStars(2),$t);$rNew=Rating::create(new RatingId('rating-a-new'),$userA,$work,new ReadingRoundId('projection-round'),RatingValue::fromStars(5),$t->modify('+1 second'));$rB=Rating::create(new RatingId('rating-b'),$userB,$work,null,RatingValue::fromStars(3.5),$t);$review=WrittenReview::create(new ReviewId('review-a'),$userA,$work,new ReadingRoundId('projection-round'),ReviewContent::fromString('<img src=x onerror=alert(1)>'),$t);
        $pOld=ContributionPublication::forRating(new PublicationId('pub-old'),$library,$rOld->id(),$t);$pNew=ContributionPublication::forRating(new PublicationId('pub-new'),$library,$rNew->id(),$t);$pB=ContributionPublication::forRating(new PublicationId('pub-b'),$library,$rB->id(),$t);$pReview=ContributionPublication::forReview(new PublicationId('pub-review'),$library,$review->id(),$t);
        $tx->run(function()use($ratings,$reviews,$publications,$userA,$userB,$rOld,$rNew,$rB,$review,$pOld,$pNew,$pB,$pReview):void{$ratings->addForUser($userA,$rOld);$ratings->addForUser($userA,$rNew);$ratings->addForUser($userB,$rB);$reviews->addForUser($userA,$review);foreach([$pOld,$pNew,$pB,$pReview] as $p)$publications->add($p);});
        $aggregate=$publications->publicAverage($library,$work);self::assertSame(2,$aggregate->count());self::assertSame(17,$aggregate->sumHalfUnits());self::assertSame(4.3,$aggregate->average());$publicReviews=$publications->publicReviews($library,$work);self::assertCount(1,$publicReviews);self::assertSame(10,$publicReviews[0]->rating()?->halfUnits());self::assertStringContainsString('&lt;img',$publicReviews[0]->escapedText());self::assertStringNotContainsString('<img',$publicReviews[0]->escapedText());
        $hidden=$pNew->moderate(ModerationStatus::Hidden,new ModerationReason('temporary'),$userB,$t->modify('+2 seconds'));self::assertTrue($tx->run(fn():bool=>$publications->replaceIfVersionMatches($hidden,$pNew->version())));self::assertSame(11,$publications->publicAverage($library,$work)->sumHalfUnits());self::assertNull($publications->publicReviews($library,$work)[0]->rating());
        $this->database->delete($this->tableNames->items(),['item_id'=>'projection-item']);self::assertSame(0,$publications->publicAverage($library,$work)->count());self::assertSame([],$publications->publicReviews($library,$work));$this->insertItem();self::assertSame(2,$publications->publicAverage($library,$work)->count());
    }
    /** @return array{UserId,UserId} */ private function createUsers():array{$suffix=bin2hex(random_bytes(4));$a=wp_insert_user(['user_login'=>'rating-a-'.$suffix,'user_pass'=>'secret','display_name'=>'Reader A']);$b=wp_insert_user(['user_login'=>'rating-b-'.$suffix,'user_pass'=>'secret','display_name'=>'Reader B']);self::assertIsInt($a);self::assertIsInt($b);$this->createdUsers=[(int)$a,(int)$b];return[new UserId((string)$a),new UserId((string)$b)];}
    private function seedLibraryWork(UserId $userA):void{$this->database->insert($this->tableNames->libraries(),['library_id'=>'projection-library','library_type'=>'private_library','library_status'=>'active']);$this->database->insert($this->tableNames->works(),['work_id'=>'projection-work','work_title'=>'Projection']);$this->database->insert($this->tableNames->editions(),['edition_id'=>'projection-edition','work_id'=>'projection-work']);$this->insertItem();$this->database->insert($this->tableNames->readingRounds(),['reading_round_id'=>'projection-round','user_id'=>$userA->value(),'work_id'=>'projection-work','item_id'=>null,'external_loan_id'=>null,'started_at'=>null,'round_outcome'=>'completed','provenance'=>'historical_manual','reading_started_year'=>2026,'reading_started_month'=>8,'reading_started_day'=>1,'reading_finished_year'=>2026,'reading_finished_month'=>8,'reading_finished_day'=>2,'created_at'=>'2026-08-22 10:00:00.000000','updated_at'=>'2026-08-22 10:00:00.000000','ended_at'=>'2026-08-22 10:00:00.000000','round_version'=>1]);}
    private function insertItem():void{$this->database->insert($this->tableNames->items(),['item_id'=>'projection-item','library_id'=>'projection-library','edition_id'=>'projection-edition','item_status'=>'active']);}
}
