<?php
declare(strict_types=1);
namespace Biblio\Core\Tests\Integration;
use Biblio\Core\Application\Reading\ContributionRoundDeletionChoice;use Biblio\Core\Assessments\{AssessmentStale,ContributionDuplicate,ModerationReason,ModerationStatus,PublicationIneligible,RatingNotAvailable,RatingValue,ReviewContent};use Biblio\Core\Catalog\WorkId;use Biblio\Core\Infrastructure\WordPress\ProductionComposition;use Biblio\Core\Library\LibraryId;use Biblio\Core\Reading\{ReadingRoundId,ReadingRoundVersion};
final class RatingsReviewsApplicationTest extends PersistenceIntegrationTestCase
{
    /** @var list<int> */ private array $users=[];
    protected function tearDown():void{wp_set_current_user(0);foreach($this->users as $id){$this->database->delete($this->database->usermeta,['user_id'=>$id]);$this->database->delete($this->database->users,['ID'=>$id]);}parent::tearDown();}
    public function testProductionServicesEnforceOwnerPublicationModerationAndCas():void
    {
        [$author,$owner]=$this->seed();$application=(new ProductionComposition($this->database))->application();$work=new WorkId('application-work');$library=new LibraryId('application-library');wp_set_current_user($author);
        $rating=$application->ratingForWorkCreation()->create($work,RatingValue::fromStars(4));$same=$application->ratingValueUpdate()->update($rating->id(),$rating->version(),RatingValue::fromStars(4));self::assertSame(1,$same->version()->value());$updated=$application->ratingValueUpdate()->update($rating->id(),$rating->version(),RatingValue::fromStars(4.5));self::assertSame(2,$updated->version()->value());try{$application->ratingValueUpdate()->update($rating->id(),$rating->version(),RatingValue::fromStars(5));self::fail('Divergent stale write accepted.');}catch(AssessmentStale){self::addToAssertionCount(1);}
        $review=$application->reviewForWorkCreation()->create($work,ReviewContent::fromString('<script>alert(1)</script>'));$ratingPublication=$application->ratingPublication()->publish($updated->id(),$library);$samePublication=$application->ratingPublication()->publish($updated->id(),$library);self::assertSame($ratingPublication->id()->value(),$samePublication->id()->value());self::assertSame(1,$samePublication->version()->value());$reviewPublication=$application->reviewPublication()->publish($review->id(),$library);self::assertCount(1,$application->assessmentQueries()->publicReviews($library,$work));self::assertStringContainsString('&lt;script',$application->assessmentQueries()->publicReviews($library,$work)[0]->escapedText());
        wp_set_current_user($owner);try{$application->assessmentQueries()->ownRating($updated->id());self::fail('Library Owner read private source.');}catch(RatingNotAvailable){self::addToAssertionCount(1);}$hidden=$application->publicationModeration()->moderate($reviewPublication->id(),$library,$reviewPublication->version(),ModerationStatus::Hidden,new ModerationReason('<b>Library rule</b>'));self::assertSame('&lt;b&gt;Library rule&lt;/b&gt;',$application->assessmentQueries()->moderationState($hidden->id(),$library)->escapedModerationReason());self::assertSame([],$application->assessmentQueries()->publicReviews($library,$work));$restored=$application->publicationRestoration()->restore($hidden->id(),$library,$hidden->version());self::assertCount(1,$application->assessmentQueries()->publicReviews($library,$work));
        wp_set_current_user($author);self::assertSame('visible',$application->assessmentQueries()->ownPublicationState($restored->id())->moderationStatus()->value);$withdrawn=$application->publicationWithdrawal()->withdraw($restored->id(),$restored->version());self::assertSame([],$application->assessmentQueries()->publicReviews($library,$work));self::assertSame('active',$ratingPublication->authorStatus()->value);self::assertSame('withdrawn',$withdrawn->authorStatus()->value);
    }
    public function testInactiveMembershipAndMissingWorkPresenceRejectPublication():void{[$author]=$this->seed();$application=(new ProductionComposition($this->database))->application();wp_set_current_user($author);$rating=$application->ratingForWorkCreation()->create(new WorkId('application-work'),RatingValue::fromStars(3));$this->database->update($this->tableNames->memberships(),['membership_status'=>'inactive'],['library_id'=>'application-library','user_id'=>(string)$author]);$this->expectException(PublicationIneligible::class);$application->ratingPublication()->publish($rating->id(),new LibraryId('application-library'));}
    public function testHistoricalRoundDeleteRequiresAndAppliesExplicitAtomicChoices():void{[$author]=$this->seed();$this->insertHistoricalRound($author,'application-round');$application=(new ProductionComposition($this->database))->application();wp_set_current_user($author);$rating=$application->ratingForRoundCreation()->create(new ReadingRoundId('application-round'),RatingValue::fromStars(4));$review=$application->reviewForRoundCreation()->create(new ReadingRoundId('application-round'),ReviewContent::fromString('keep'));$application->historicalReadingRoundDeletion()->delete(new ReadingRoundId('application-round'),new ReadingRoundVersion(1),ContributionRoundDeletionChoice::DeleteContribution,ContributionRoundDeletionChoice::PreserveUnlinked);self::assertSame(0,(int)$this->database->get_var("SELECT COUNT(*) FROM `{$this->tableNames->readingRounds()}` WHERE reading_round_id='application-round'"));self::assertSame(1,(int)$this->database->get_var("SELECT COUNT(*) FROM `{$this->tableNames->works()}` WHERE work_id='application-work'"));try{$application->assessmentQueries()->ownRating($rating->id());self::fail('Deleted Rating remained.');}catch(RatingNotAvailable){self::addToAssertionCount(1);}$kept=$application->assessmentQueries()->ownReview($review->id());self::assertNull($kept->readingRoundId());self::assertSame(2,$kept->version()->value());}
    public function testRoundUnlinkCardinalityConflictRollsBackEverything():void{[$author]=$this->seed();$this->insertHistoricalRound($author,'conflict-round');$application=(new ProductionComposition($this->database))->application();wp_set_current_user($author);$application->ratingForWorkCreation()->create(new WorkId('application-work'),RatingValue::fromStars(2));$linked=$application->ratingForRoundCreation()->create(new ReadingRoundId('conflict-round'),RatingValue::fromStars(4));try{$application->historicalReadingRoundDeletion()->delete(new ReadingRoundId('conflict-round'),new ReadingRoundVersion(1),ContributionRoundDeletionChoice::PreserveUnlinked,null);self::fail('Unlinked conflict accepted.');}catch(ContributionDuplicate){self::addToAssertionCount(1);}self::assertSame(1,(int)$this->database->get_var("SELECT COUNT(*) FROM `{$this->tableNames->readingRounds()}` WHERE reading_round_id='conflict-round'"));self::assertSame('conflict-round',$application->assessmentQueries()->ownRating($linked->id())->readingRoundId()?->value());}
    /** @return array{int,int} */ private function seed():array{$suffix=bin2hex(random_bytes(4));$author=wp_insert_user(['user_login'=>'app-author-'.$suffix,'user_pass'=>'secret','display_name'=>'Author']);$owner=wp_insert_user(['user_login'=>'app-owner-'.$suffix,'user_pass'=>'secret','display_name'=>'Owner']);self::assertIsInt($author);self::assertIsInt($owner);$this->users=[(int)$author,(int)$owner];$this->database->insert($this->tableNames->libraries(),['library_id'=>'application-library','library_name'=>'Applicationbibliotheek','library_type'=>'private_library','library_status'=>'active']);foreach([[(string)$author,'member','view_only'],[(string)$owner,'owner','direct']] as [$user,$role,$access])$this->database->insert($this->tableNames->memberships(),['library_id'=>'application-library','user_id'=>$user,'membership_status'=>'active','management_role'=>$role,'use_access'=>$access,'additional_permissions'=>'[]']);$this->database->insert($this->tableNames->works(),['work_id'=>'application-work','work_title'=>'Application']);$this->database->insert($this->tableNames->editions(),['edition_id'=>'application-edition','work_id'=>'application-work']);$this->database->insert($this->tableNames->items(),['item_id'=>'application-item','library_id'=>'application-library','edition_id'=>'application-edition','item_status'=>'active']);return[(int)$author,(int)$owner];}
    private function insertHistoricalRound(int $user,string $id):void{$this->database->insert($this->tableNames->readingRounds(),['reading_round_id'=>$id,'user_id'=>(string)$user,'work_id'=>'application-work','item_id'=>null,'external_loan_id'=>null,'started_at'=>null,'round_outcome'=>'completed','provenance'=>'historical_manual','reading_started_year'=>2026,'reading_started_month'=>8,'reading_started_day'=>1,'reading_finished_year'=>2026,'reading_finished_month'=>8,'reading_finished_day'=>2,'created_at'=>'2026-08-22 10:00:00.000000','updated_at'=>'2026-08-22 10:00:00.000000','ended_at'=>'2026-08-22 10:00:00.000000','round_version'=>1]);}
}
