<?php
declare(strict_types=1);
namespace Biblio\Core\Tests\Integration;
use Biblio\Core\Assessments\{AuthorStatus,ContributionDuplicate,ContributionPublication,ModerationStatus,PublicationId,Rating,RatingId,RatingValue,ReviewContent,ReviewId,WrittenReview};
use Biblio\Core\Catalog\WorkId;use Biblio\Core\Identity\UserId;use Biblio\Core\Infrastructure\Persistence\WordPress\{WpdbPublicationRepository,WpdbRatingRepository,WpdbReviewRepository,WpdbTransactionConnection,WpdbTransactionManager};use Biblio\Core\Infrastructure\Persistence\WordPress\Schema\{CoreSchema1005Migration,CoreSchemaMigrationException,CoreSchemaMigrator};use Biblio\Core\Library\LibraryId;use Biblio\Core\Reading\ReadingRoundId;use DateTimeImmutable;
final class Schema1005RatingsReviewsTest extends PersistenceIntegrationTestCase
{
    public function testSchema1005IsHealthyAndHasTheThreeExactTables():void{$health=$this->migrator()->healthForVersion(1005);self::assertTrue($health->isHealthy(),$health->summary());self::assertSame(9,$this->columnCount($this->tableNames->ratings()));self::assertSame(9,$this->columnCount($this->tableNames->reviews()));self::assertSame(14,$this->columnCount($this->tableNames->contributionPublications()));self::assertSame('RESTRICT',$this->deleteRule($this->tableNames->ratings(),'reading_round_id'));self::assertSame('CASCADE',$this->deleteRule($this->tableNames->contributionPublications(),'rating_id'));}
    public function testRatingReviewPublicationRoundTripUniquenessCasAndCascade():void{$this->seedContext();$tx=new WpdbTransactionManager(new WpdbTransactionConnection($this->database));$ratings=new WpdbRatingRepository($this->database,$this->tableNames);$reviews=new WpdbReviewRepository($this->database,$this->tableNames);$publications=new WpdbPublicationRepository($this->database,$this->tableNames);$now=new DateTimeImmutable('2026-08-22T12:34:56.123456+00:00');$user=new UserId('501');$rating=Rating::create(new RatingId('rating-roundtrip'),$user,new WorkId('work-assessment'),new ReadingRoundId('round-assessment'),RatingValue::fromStars(4.5),$now);$review=WrittenReview::create(new ReviewId('review-roundtrip'),$user,new WorkId('work-assessment'),null,ReviewContent::fromString("<script>x</script>\r\n🙂"),$now);$publication=ContributionPublication::forRating(new PublicationId('publication-roundtrip'),new LibraryId('library-assessment'),$rating->id(),$now);$tx->run(function()use($ratings,$reviews,$publications,$user,$rating,$review,$publication):void{$ratings->addForUser($user,$rating);$reviews->addForUser($user,$review);$publications->add($publication);});$stored=$ratings->findForUser($rating->id(),$user);self::assertNotNull($stored);self::assertSame(9,$stored->value()->halfUnits());self::assertSame('round-assessment',$stored->readingRoundId()?->value());self::assertSame("<script>x</script>\n🙂",$reviews->findForUser($review->id(),$user)?->content()->value());$changed=$stored->withValue(RatingValue::fromStars(5),$now->modify('+1 second'));self::assertTrue($tx->run(fn():bool=>$ratings->replaceIfVersionMatches($user,$changed,$stored->version())));self::assertFalse($tx->run(fn():bool=>$ratings->replaceIfVersionMatches($user,$changed,$stored->version())));self::assertTrue($tx->run(fn():bool=>$ratings->deleteIfVersionMatches($user,$rating->id(),$changed->version())));self::assertSame(0,(int)$this->database->get_var("SELECT COUNT(*) FROM `{$this->tableNames->contributionPublications()}`"));}
    public function testOneUnlinkedAndOnePerRoundConstraintsAreTranslated():void{$this->seedContext();$repo=new WpdbRatingRepository($this->database,$this->tableNames);$tx=new WpdbTransactionManager(new WpdbTransactionConnection($this->database));$now=new DateTimeImmutable('2026-08-22T12:00:00+00:00');$user=new UserId('501');$first=Rating::create(new RatingId('rating-first'),$user,new WorkId('work-assessment'),null,RatingValue::fromStars(3),$now);$second=Rating::create(new RatingId('rating-second'),$user,new WorkId('work-assessment'),null,RatingValue::fromStars(4),$now);$tx->run(fn()=>$repo->addForUser($user,$first));$this->expectException(ContributionDuplicate::class);$tx->run(fn()=>$repo->addForUser($user,$second));}
    public function testKnownRetryConvergesAndUnknownPartialStateFailsClosed():void{$migration=new CoreSchema1005Migration($this->database,$this->tableNames);$migration->assertPrecondition();$migration->migrate();$migration->assertPostcondition();$table=$this->tableNames->contributionPublications();$reviews=$this->tableNames->reviews();$this->database->query("DROP TABLE `{$table}`");$this->database->query("DROP TABLE `{$reviews}`");update_option(CoreSchemaMigrator::VERSION_OPTION,'1004',false);$known=new CoreSchema1005Migration($this->database,$this->tableNames);$known->assertPrecondition();$known->migrate();$known->assertPostcondition();self::assertTrue($this->migrator()->healthForVersion(1005)->isHealthy());$this->database->query("DROP TABLE `{$table}`");$this->database->query("CREATE TABLE `{$table}` (publication_id VARCHAR(191) NOT NULL PRIMARY KEY) ENGINE=InnoDB");update_option(CoreSchemaMigrator::VERSION_OPTION,'1004',false);try{(new CoreSchema1005Migration($this->database,$this->tableNames))->assertPrecondition();self::fail('Unknown partial state accepted.');}catch(CoreSchemaMigrationException $e){self::assertStringContainsString('unknown partial',$e->getMessage());}finally{$this->database->query("DROP TABLE `{$table}`");update_option(CoreSchemaMigrator::VERSION_OPTION,'1004',false);$this->migrator()->migrate();}}
    private function seedContext():void{$this->database->insert($this->tableNames->works(),['work_id'=>'work-assessment','work_title'=>'Assessment']);$this->database->insert($this->tableNames->readingRounds(),['reading_round_id'=>'round-assessment','user_id'=>'501','work_id'=>'work-assessment','item_id'=>null,'external_loan_id'=>null,'started_at'=>null,'round_outcome'=>'completed','provenance'=>'historical_manual','reading_started_year'=>2026,'reading_started_month'=>8,'reading_started_day'=>1,'reading_finished_year'=>2026,'reading_finished_month'=>8,'reading_finished_day'=>2,'created_at'=>'2026-08-22 10:00:00.000000','updated_at'=>'2026-08-22 10:00:00.000000','ended_at'=>'2026-08-22 10:00:00.000000','round_version'=>1]);$this->database->insert($this->tableNames->libraries(),['library_id'=>'library-assessment','library_name'=>'Assessmentbibliotheek','library_type'=>'private_library','library_status'=>'active']);}
    private function migrator():CoreSchemaMigrator{return new CoreSchemaMigrator($this->database,$this->tableNames,\Biblio\Core\Infrastructure\Persistence\WordPress\Schema\CoreSchemaMigrationRegistry::production($this->database,$this->tableNames)->migrations());}
    private function columnCount(string $table):int{return(int)$this->database->get_var($this->database->prepare('SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=%s AND TABLE_NAME=%s',DB_NAME,$table));}
    private function deleteRule(string $table,string $column):string{return(string)$this->database->get_var($this->database->prepare('SELECT r.DELETE_RULE FROM information_schema.KEY_COLUMN_USAGE k INNER JOIN information_schema.REFERENTIAL_CONSTRAINTS r ON r.CONSTRAINT_SCHEMA=k.CONSTRAINT_SCHEMA AND r.TABLE_NAME=k.TABLE_NAME AND r.CONSTRAINT_NAME=k.CONSTRAINT_NAME WHERE k.CONSTRAINT_SCHEMA=%s AND k.TABLE_NAME=%s AND k.COLUMN_NAME=%s',DB_NAME,$table,$column));}
}
