<?php
declare(strict_types=1);
namespace Biblio\Core\Tests\Unit;
use Biblio\Core\Assessments\{AuthorStatus,ContributionPublication,ModerationReason,ModerationStatus,PublicationId,Rating,RatingAggregate,RatingId,RatingValue,ReviewContent,ReviewId,WrittenReview};
use Biblio\Core\Catalog\WorkId;use Biblio\Core\Exception\ValidationException;use Biblio\Core\Identity\UserId;use Biblio\Core\Library\LibraryId;use Biblio\Core\Reading\ReadingRoundId;use DateTimeImmutable;use PHPUnit\Framework\Attributes\DataProvider;use PHPUnit\Framework\TestCase;
final class AssessmentsTest extends TestCase
{
    /** @return iterable<string,array{float,int}> */ public static function validRatings():iterable{foreach([[1.0,2],[1.5,3],[2.0,4],[2.5,5],[3.0,6],[3.5,7],[4.0,8],[4.5,9],[5.0,10]] as [$stars,$units])yield (string)$stars=>[$stars,$units];}
    #[DataProvider('validRatings')] public function testExactRatingScaleRoundTrips(float $stars,int $units):void{$rating=RatingValue::fromStars($stars);self::assertSame($units,$rating->halfUnits());self::assertSame($stars,$rating->stars());self::assertTrue($rating->equals(RatingValue::fromHalfUnits($units)));}
    /** @return iterable<string,array{float}> */ public static function invalidRatings():iterable{foreach([-1.0,0.0,0.5,1.1,5.1,6.0,INF,NAN] as $value)yield (string)$value=>[$value];}
    #[DataProvider('invalidRatings')] public function testInvalidRatingsFail(float $stars):void{$this->expectException(ValidationException::class);RatingValue::fromStars($stars);}
    public function testReviewNormalizesLinesMeasuresCodePointsAndEscapesMarkup():void{$content=ReviewContent::fromString("é\r\n<script onclick=alert(1)>x</script>\r");self::assertSame("é\n<script onclick=alert(1)>x</script>\n",$content->value());self::assertStringNotContainsString('<script',$content->escaped());self::assertStringContainsString('&lt;script',$content->escaped());self::assertSame(str_repeat('🙂',5000),ReviewContent::fromString(str_repeat('🙂',5000))->value());}
    public function testReviewRejectsInvalidNulAndOverLimit():void{foreach(["bad\0value",str_repeat('🙂',5001),"\xC3\x28"] as $invalid){try{ReviewContent::fromString($invalid);self::fail('Invalid review accepted.');}catch(ValidationException){self::addToAssertionCount(1);}}}
    public function testSeparateAggregatesKeepOwnerAndWorkImmutableAndIncrementOnce():void{$now=new DateTimeImmutable('2026-08-22T10:00:00.000000+00:00');$rating=Rating::create(new RatingId('rating-a'),new UserId('user-a'),new WorkId('work-a'),null,RatingValue::fromStars(4.0),$now);$review=WrittenReview::create(new ReviewId('review-a'),new UserId('user-a'),new WorkId('work-a'),new ReadingRoundId('round-a'),ReviewContent::fromString('text'),$now);$next=$rating->withReadingRound(new ReadingRoundId('round-a'),$now->modify('+1 second'));self::assertSame(2,$next->version()->value());self::assertSame('user-a',$next->userId()->value());self::assertSame('work-a',$next->workId()->value());self::assertSame(1,$review->version()->value());}
    public function testPublicationXorLifecycleAndTerminalModeration():void{$now=new DateTimeImmutable('2026-08-22T10:00:00.000000+00:00');$p=ContributionPublication::forRating(new PublicationId('publication-a'),new LibraryId('library-a'),new RatingId('rating-a'),$now);self::assertSame(AuthorStatus::Active,$p->authorStatus());$hidden=$p->moderate(ModerationStatus::Hidden,new ModerationReason('privacy'),new UserId('moderator-a'),$now->modify('+1 second'));self::assertSame(2,$hidden->version()->value());self::assertSame(ModerationStatus::Visible,$hidden->restore($now->modify('+2 seconds'))->moderationStatus());$removed=$p->moderate(ModerationStatus::Removed,new ModerationReason('abuse'),new UserId('moderator-a'),$now->modify('+1 second'));$this->expectException(ValidationException::class);$removed->restore($now->modify('+2 seconds'));}
    public function testAggregateUsesExactScaledSumAndHalfUpPresentation():void{$aggregate=new RatingAggregate(3,17,2);self::assertSame(17,$aggregate->sumHalfUnits());self::assertSame(2.8,$aggregate->average());self::assertNull(RatingAggregate::empty()->average());}
}
