<?php
declare(strict_types=1);
namespace Biblio\Core\Infrastructure\Persistence\WordPress;
use Biblio\Core\Application\Assessments\Read\{PublicAssessmentCursor,PublicAssessmentKind,PublicAssessmentPage,PublicAssessmentPageSize,PublicAssessmentReadRepository,PublicAssessmentView};
use Biblio\Core\Assessments\{AuthorStatus,ContributionDuplicate,ContributionPublication,ModerationReason,ModerationStatus,PublicationId,PublicationIdCollision,PublicationVersion,PublicRating,PublicReview,RatingAggregate,RatingId,RatingValue,ReviewContent,ReviewId,WritablePublicationRepository};
use Biblio\Core\Catalog\WorkId; use Biblio\Core\Exception\FailureReason; use Biblio\Core\Identity\UserId; use Biblio\Core\Infrastructure\Persistence\PersistenceException; use Biblio\Core\Library\LibraryId; use DateTimeImmutable; use DateTimeZone; use Throwable; use wpdb;
final readonly class WpdbPublicationRepository implements WritablePublicationRepository, PublicAssessmentReadRepository
{
    private const FORMAT='Y-m-d H:i:s.u';
    public function __construct(private wpdb $db,private CoreTableNames $tables) {}
    public function add(ContributionPublication $p):void{$old=$this->db->suppress_errors(true);try{$ok=$this->db->insert($this->tables->contributionPublications(),$this->data($p),['%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%d']);}finally{$this->db->suppress_errors($old);}if($ok===1)return;$conflict=WpdbErrorTranslator::conflict($this->db->last_error);if($conflict?->constraintName()==='PRIMARY')throw new PublicationIdCollision();if($conflict!==null)throw new ContributionDuplicate();throw WpdbErrorTranslator::writeFailure('Could not persist Publication.',$this->db->last_error);}
    public function findForOwnerForUpdate(PublicationId $id,UserId $owner):?ContributionPublication{$p=$this->tables->contributionPublications();$r=$this->tables->ratings();$v=$this->tables->reviews();$row=$this->db->get_row($this->db->prepare("SELECT p.* FROM `{$p}` p LEFT JOIN `{$r}` r ON r.rating_id=p.rating_id LEFT JOIN `{$v}` v ON v.review_id=p.review_id WHERE p.publication_id=%s AND COALESCE(r.user_id,v.user_id)=%s FOR UPDATE",$id->value(),$owner->value()));return $row===null?null:$this->hydrate($row);}
    public function findForOwner(PublicationId $id,UserId $owner):?ContributionPublication{$p=$this->tables->contributionPublications();$r=$this->tables->ratings();$v=$this->tables->reviews();$row=$this->db->get_row($this->db->prepare("SELECT p.* FROM `{$p}` p LEFT JOIN `{$r}` r ON r.rating_id=p.rating_id LEFT JOIN `{$v}` v ON v.review_id=p.review_id WHERE p.publication_id=%s AND COALESCE(r.user_id,v.user_id)=%s",$id->value(),$owner->value()));return $row===null?null:$this->hydrate($row);}
    public function findInLibraryForUpdate(PublicationId $id,LibraryId $library):?ContributionPublication{$t=$this->tables->contributionPublications();$row=$this->db->get_row($this->db->prepare("SELECT * FROM `{$t}` WHERE publication_id=%s AND library_id=%s FOR UPDATE",$id->value(),$library->value()));return $row===null?null:$this->hydrate($row);}
    public function findInLibrary(PublicationId $id,LibraryId $library):?ContributionPublication{$t=$this->tables->contributionPublications();$row=$this->db->get_row($this->db->prepare("SELECT * FROM `{$t}` WHERE publication_id=%s AND library_id=%s",$id->value(),$library->value()));return $row===null?null:$this->hydrate($row);}
    public function findRatingHistory(RatingId $id,LibraryId $library):?ContributionPublication{return $this->history('rating_id',$id->value(),$library);} public function findReviewHistory(ReviewId $id,LibraryId $library):?ContributionPublication{return $this->history('review_id',$id->value(),$library);}
    public function replaceIfVersionMatches(ContributionPublication $p,PublicationVersion $expected):bool{if($p->version()->value()!==$expected->value()+1)throw new PersistenceException('Publication replacement must increment once.',failureReason:FailureReason::PersistenceWriteFailed);$t=$this->tables->contributionPublications();$d=$this->data($p);$result=$this->db->update($t,array_slice($d,4),['publication_id'=>$p->id()->value(),'publication_version'=>$expected->value()],['%s','%s','%s','%s','%s','%s','%s','%d'],['%s','%d']);if($result===false){if(WpdbErrorTranslator::conflict($this->db->last_error)!==null)throw new ContributionDuplicate();throw WpdbErrorTranslator::writeFailure('Could not update Publication.',$this->db->last_error);}return $result===1;}
    public function publicRatings(LibraryId $library,WorkId $work):array{$p=$this->tables->contributionPublications();$r=$this->tables->ratings();$i=$this->tables->items();$e=$this->tables->editions();$u=$this->db->users;$rows=$this->db->get_results($this->db->prepare("SELECT u.display_name,r.rating_half_units,p.published_at FROM `{$p}` p INNER JOIN `{$r}` r ON r.rating_id=p.rating_id INNER JOIN `{$u}` u ON CAST(u.ID AS CHAR)=r.user_id WHERE p.library_id=%s AND r.work_id=%s AND p.author_status='active' AND p.moderation_status='visible' AND EXISTS (SELECT 1 FROM `{$i}` i INNER JOIN `{$e}` e ON e.edition_id=i.edition_id WHERE i.library_id=p.library_id AND i.item_status='active' AND e.work_id=r.work_id) ORDER BY p.updated_at DESC,p.publication_id DESC",$library->value(),$work->value()));return array_map(fn(object $x):PublicRating=>new PublicRating((string)$x->display_name,RatingValue::fromHalfUnits((int)$x->rating_half_units),$this->date($x->published_at)),$rows);}
    public function publicReviews(LibraryId $library,WorkId $work):array{$p=$this->tables->contributionPublications();$reviews=$this->tables->reviews();$ratings=$this->tables->ratings();$i=$this->tables->items();$e=$this->tables->editions();$u=$this->db->users;$rows=$this->db->get_results($this->db->prepare("SELECT u.display_name,v.review_content,p.published_at,(SELECT r.rating_half_units FROM `{$ratings}` r INNER JOIN `{$p}` rp ON rp.rating_id=r.rating_id WHERE r.user_id=v.user_id AND r.work_id=v.work_id AND (r.reading_round_id <=> v.reading_round_id) AND rp.library_id=p.library_id AND rp.author_status='active' AND rp.moderation_status='visible' LIMIT 1) associated_rating FROM `{$p}` p INNER JOIN `{$reviews}` v ON v.review_id=p.review_id INNER JOIN `{$u}` u ON CAST(u.ID AS CHAR)=v.user_id WHERE p.library_id=%s AND v.work_id=%s AND p.author_status='active' AND p.moderation_status='visible' AND EXISTS (SELECT 1 FROM `{$i}` i INNER JOIN `{$e}` e ON e.edition_id=i.edition_id WHERE i.library_id=p.library_id AND i.item_status='active' AND e.work_id=v.work_id) ORDER BY p.updated_at DESC,p.publication_id DESC",$library->value(),$work->value()));return array_map(fn(object $x):PublicReview=>new PublicReview((string)$x->display_name,$x->associated_rating===null?null:RatingValue::fromHalfUnits((int)$x->associated_rating),ReviewContent::fromString((string)$x->review_content)->escaped(),$this->date($x->published_at)),$rows);}
    public function publicAverage(LibraryId $library,WorkId $work):RatingAggregate{$p=$this->tables->contributionPublications();$r=$this->tables->ratings();$i=$this->tables->items();$e=$this->tables->editions();$rows=$this->db->get_results($this->db->prepare("SELECT r.user_id,r.rating_half_units FROM `{$p}` p INNER JOIN `{$r}` r ON r.rating_id=p.rating_id WHERE p.library_id=%s AND r.work_id=%s AND p.author_status='active' AND p.moderation_status='visible' AND EXISTS (SELECT 1 FROM `{$i}` i INNER JOIN `{$e}` e ON e.edition_id=i.edition_id WHERE i.library_id=p.library_id AND i.item_status='active' AND e.work_id=r.work_id) ORDER BY r.user_id,r.updated_at DESC,r.rating_id DESC",$library->value(),$work->value()));$seen=[];$sum=0;foreach($rows as $row){$user=(string)$row->user_id;if(isset($seen[$user]))continue;$seen[$user]=true;$sum+=(int)$row->rating_half_units;}return new RatingAggregate(count($seen),$sum,count($seen));}
    public function forLibraryAndWork(LibraryId $library,WorkId $work,PublicAssessmentPageSize $pageSize,?PublicAssessmentCursor $cursor):PublicAssessmentPage
    {
        $p=$this->tables->contributionPublications();$r=$this->tables->ratings();$v=$this->tables->reviews();$i=$this->tables->items();$e=$this->tables->editions();$u=$this->db->users;
        $presence="EXISTS (SELECT 1 FROM `{$i}` i INNER JOIN `{$e}` e ON e.edition_id=i.edition_id WHERE i.library_id=public_assessments.library_id AND i.item_status='active' AND e.work_id=public_assessments.source_work_id)";
        $rating="SELECT p.publication_id,p.library_id,p.updated_at sort_updated_at,p.published_at,u.display_name,'rating' contribution_type,r.work_id source_work_id,r.rating_half_units,NULL review_content,NULL associated_rating FROM `{$p}` p INNER JOIN `{$r}` r ON r.rating_id=p.rating_id INNER JOIN `{$u}` u ON CAST(u.ID AS CHAR)=r.user_id WHERE p.library_id=%s AND r.work_id=%s AND p.author_status='active' AND p.moderation_status='visible'";
        $associated="(SELECT ar.rating_half_units FROM `{$r}` ar INNER JOIN `{$p}` ap ON ap.rating_id=ar.rating_id WHERE ar.user_id=v.user_id AND ar.work_id=v.work_id AND (ar.reading_round_id <=> v.reading_round_id) AND ap.library_id=p.library_id AND ap.author_status='active' AND ap.moderation_status='visible' ORDER BY ar.updated_at DESC,ar.rating_id DESC LIMIT 1)";
        $review="SELECT p.publication_id,p.library_id,p.updated_at sort_updated_at,p.published_at,u.display_name,'review' contribution_type,v.work_id source_work_id,NULL rating_half_units,v.review_content,{$associated} associated_rating FROM `{$p}` p INNER JOIN `{$v}` v ON v.review_id=p.review_id INNER JOIN `{$u}` u ON CAST(u.ID AS CHAR)=v.user_id WHERE p.library_id=%s AND v.work_id=%s AND p.author_status='active' AND p.moderation_status='visible'";
        $sql="SELECT * FROM ({$rating} UNION ALL {$review}) public_assessments WHERE {$presence}";
        $parameters=[$library->value(),$work->value(),$library->value(),$work->value()];
        if($cursor!==null){$sql.=" AND (sort_updated_at < %s OR (sort_updated_at = %s AND publication_id < %s))";$formatted=$this->format($cursor->beforeUpdatedAt());$parameters[]=$formatted;$parameters[]=$formatted;$parameters[]=$cursor->beforePublicationId()->value();}
        $sql.=" ORDER BY sort_updated_at DESC,publication_id DESC LIMIT %d";$parameters[]=$pageSize->value()+1;
        $rows=$this->db->get_results($this->db->prepare($sql,...$parameters));
        if(!is_array($rows)||$this->db->last_error!=="")throw new PersistenceException('Could not read public assessments.',0,WpdbErrorTranslator::diagnostic('Public assessment projection',$this->db->last_error),FailureReason::PersistenceReadFailed);
        $hasMore=count($rows)>$pageSize->value();if($hasMore)$rows=array_slice($rows,0,$pageSize->value());
        try{$entries=array_map($this->hydratePublicAssessment(...),$rows);$last=$rows===[]?null:$rows[array_key_last($rows)];return new PublicAssessmentPage($entries,$this->publicAverage($library,$work),$hasMore&&$last!==null?new PublicAssessmentCursor($this->date($last->sort_updated_at),new PublicationId((string)$last->publication_id)):null);}catch(Throwable $e){if($e instanceof PersistenceException)throw $e;throw new PersistenceException('Stored public assessment projection data is invalid.',0,$e,FailureReason::PersistenceReadFailed);}
    }
    private function hydratePublicAssessment(object $row):PublicAssessmentView
    {
        $kind=PublicAssessmentKind::from((string)$row->contribution_type);
        $rating=$row->rating_half_units!==null?RatingValue::fromHalfUnits((int)$row->rating_half_units):($row->associated_rating===null?null:RatingValue::fromHalfUnits((int)$row->associated_rating));
        return new PublicAssessmentView($kind,(string)$row->display_name,$rating,$kind===PublicAssessmentKind::Review?ReviewContent::fromString((string)$row->review_content)->escaped():null,$this->date($row->published_at));
    }
    private function history(string $column,string $id,LibraryId $library):?ContributionPublication{$t=$this->tables->contributionPublications();$row=$this->db->get_row($this->db->prepare("SELECT * FROM `{$t}` WHERE `{$column}`=%s AND library_id=%s",$id,$library->value()));return $row===null?null:$this->hydrate($row);}
    /** @return array<string,mixed> */ private function data(ContributionPublication $p):array{return['publication_id'=>$p->id()->value(),'library_id'=>$p->libraryId()->value(),'rating_id'=>$p->ratingId()?->value(),'review_id'=>$p->reviewId()?->value(),'author_status'=>$p->authorStatus()->value,'moderation_status'=>$p->moderationStatus()->value,'moderation_reason'=>$p->moderationReason()?->value(),'moderator_user_id'=>$p->moderatorUserId()?->value(),'moderated_at'=>$p->moderatedAt()===null?null:$this->format($p->moderatedAt()),'published_at'=>$this->format($p->publishedAt()),'updated_at'=>$this->format($p->updatedAt()),'publication_version'=>$p->version()->value()];}
    private function hydrate(object $r):ContributionPublication{try{return new ContributionPublication(new PublicationId((string)$r->publication_id),new LibraryId((string)$r->library_id),$r->rating_id===null?null:new RatingId((string)$r->rating_id),$r->review_id===null?null:new ReviewId((string)$r->review_id),AuthorStatus::from((string)$r->author_status),ModerationStatus::from((string)$r->moderation_status),$r->moderation_reason===null?null:new ModerationReason((string)$r->moderation_reason),$r->moderator_user_id===null?null:new UserId((string)$r->moderator_user_id),$r->moderated_at===null?null:$this->date($r->moderated_at),$this->date($r->published_at),$this->date($r->updated_at),new PublicationVersion((int)$r->publication_version));}catch(Throwable $e){throw new PersistenceException('Stored Publication is invalid.',0,$e,FailureReason::PersistenceReadFailed);}}
    private function format(DateTimeImmutable $d):string{return $d->setTimezone(new DateTimeZone('UTC'))->format(self::FORMAT);} private function date(mixed $v):DateTimeImmutable{$d=DateTimeImmutable::createFromFormat('!'.self::FORMAT,(string)$v,new DateTimeZone('UTC'));if($d===false)throw new PersistenceException('Stored Publication instant invalid.',failureReason:FailureReason::PersistenceReadFailed);return $d;}
}
