<?php
declare(strict_types=1);
namespace Biblio\Core\Infrastructure\Persistence\WordPress;
use Biblio\Core\Assessments\{ContributionDuplicate,ReviewContent,ReviewId,ReviewIdCollision,ReviewVersion,WritableReviewRepository,WrittenReview};
use Biblio\Core\Catalog\WorkId; use Biblio\Core\Exception\{AuthorizationException,FailureReason}; use Biblio\Core\Identity\UserId; use Biblio\Core\Infrastructure\Persistence\PersistenceException; use Biblio\Core\Reading\ReadingRoundId; use DateTimeImmutable; use DateTimeZone; use Throwable; use wpdb;
final readonly class WpdbReviewRepository implements WritableReviewRepository
{
    private const FORMAT='Y-m-d H:i:s.u';
    public function __construct(private wpdb $db,private CoreTableNames $tables) {}
    public function addForUser(UserId $actor,WrittenReview $review): void { $this->assertOwner($actor,$review);$this->assertRound($review);$old=$this->db->suppress_errors(true);try{$ok=$this->db->insert($this->tables->reviews(),['review_id'=>$review->id()->value(),'user_id'=>$review->userId()->value(),'work_id'=>$review->workId()->value(),'reading_round_id'=>$review->readingRoundId()?->value(),'review_content'=>$review->content()->value(),'created_at'=>$this->format($review->createdAt()),'updated_at'=>$this->format($review->updatedAt()),'review_version'=>$review->version()->value()],['%s','%s','%s','%s','%s','%s','%s','%d']);}finally{$this->db->suppress_errors($old);}if($ok===1)return;$conflict=WpdbErrorTranslator::conflict($this->db->last_error);if($conflict?->constraintName()==='PRIMARY')throw new ReviewIdCollision();if($conflict!==null)throw new ContributionDuplicate();throw WpdbErrorTranslator::writeFailure('Could not persist Review.',$this->db->last_error); }
    public function findForUser(ReviewId $id,UserId $user):?WrittenReview{return $this->one($id,$user,false);} public function findForUserForUpdate(ReviewId $id,UserId $user):?WrittenReview{return $this->one($id,$user,true);}
    public function findForUserAndWork(UserId $u,WorkId $w):array{return $this->many('user_id=%s AND work_id=%s',[$u->value(),$w->value()]);} public function findForUserAndRound(UserId $u,ReadingRoundId $r):array{return $this->many('user_id=%s AND reading_round_id=%s',[$u->value(),$r->value()]);} public function findAllForUser(UserId $u,int $limit=50):array{return $this->many('user_id=%s',[$u->value()],max(1,min(100,$limit)));}
    public function replaceIfVersionMatches(UserId $actor,WrittenReview $r,ReviewVersion $expected):bool{$this->assertOwner($actor,$r);$this->assertRound($r);if($r->version()->value()!==$expected->value()+1)throw new PersistenceException('Review replacement must increment once.',failureReason:FailureReason::PersistenceWriteFailed);$round=$r->readingRoundId()===null?'NULL':$this->db->prepare('%s',$r->readingRoundId()->value());$t=$this->tables->reviews();$old=$this->db->suppress_errors(true);try{$result=$this->db->query($this->db->prepare("UPDATE `{$t}` SET reading_round_id={$round},review_content=%s,updated_at=%s,review_version=%d WHERE review_id=%s AND user_id=%s AND work_id=%s AND review_version=%d",$r->content()->value(),$this->format($r->updatedAt()),$r->version()->value(),$r->id()->value(),$actor->value(),$r->workId()->value(),$expected->value()));}finally{$this->db->suppress_errors($old);}if($result===false){if(WpdbErrorTranslator::conflict($this->db->last_error)!==null)throw new ContributionDuplicate();throw WpdbErrorTranslator::writeFailure('Could not update Review.',$this->db->last_error);}return $result===1;}
    public function deleteIfVersionMatches(UserId $a,ReviewId $id,ReviewVersion $e):bool{$t=$this->tables->reviews();$r=$this->db->query($this->db->prepare("DELETE FROM `{$t}` WHERE review_id=%s AND user_id=%s AND review_version=%d",$id->value(),$a->value(),$e->value()));if($r===false)throw WpdbErrorTranslator::writeFailure('Could not delete Review.',$this->db->last_error);return $r===1;}
    private function one(ReviewId $id,UserId $u,bool $lock):?WrittenReview{$t=$this->tables->reviews();$row=$this->db->get_row($this->db->prepare("SELECT review_id,user_id,work_id,reading_round_id,review_content,created_at,updated_at,review_version FROM `{$t}` WHERE review_id=%s AND user_id=%s".($lock?' FOR UPDATE':''),$id->value(),$u->value()));return $row===null?null:$this->hydrate($row);}
    /**
     * @param list<string|int> $args
     * @return list<WrittenReview>
     */
    private function many(string $where,array $args,int $limit=100):array{$t=$this->tables->reviews();$args[]=$limit;$rows=$this->db->get_results($this->db->prepare("SELECT review_id,user_id,work_id,reading_round_id,review_content,created_at,updated_at,review_version FROM `{$t}` WHERE {$where} ORDER BY updated_at DESC,review_id DESC LIMIT %d",...$args));return array_map($this->hydrate(...),$rows);}
    private function hydrate(object $r):WrittenReview{try{return new WrittenReview(new ReviewId((string)$r->review_id),new UserId((string)$r->user_id),new WorkId((string)$r->work_id),$r->reading_round_id===null?null:new ReadingRoundId((string)$r->reading_round_id),ReviewContent::fromString((string)$r->review_content),$this->date($r->created_at),$this->date($r->updated_at),new ReviewVersion((int)$r->review_version));}catch(Throwable $e){throw new PersistenceException('Stored Review is invalid.',0,$e,FailureReason::PersistenceReadFailed);}}
    private function assertOwner(UserId $a,WrittenReview $r):void{if(!$a->equals($r->userId()))throw new AuthorizationException('Cannot persist Review for another user.');} private function assertRound(WrittenReview $r):void{if($r->readingRoundId()===null)return;$t=$this->tables->readingRounds();$m=$this->db->get_var($this->db->prepare("SELECT reading_round_id FROM `{$t}` WHERE reading_round_id=%s AND user_id=%s AND work_id=%s",$r->readingRoundId()->value(),$r->userId()->value(),$r->workId()->value()));if(!is_string($m))throw new PersistenceException('Review ReadingRound context is inconsistent.',failureReason:FailureReason::PersistenceWriteFailed);} private function format(DateTimeImmutable $d):string{return $d->setTimezone(new DateTimeZone('UTC'))->format(self::FORMAT);} private function date(mixed $v):DateTimeImmutable{$d=DateTimeImmutable::createFromFormat('!'.self::FORMAT,(string)$v,new DateTimeZone('UTC'));if($d===false)throw new PersistenceException('Stored Review instant invalid.',failureReason:FailureReason::PersistenceReadFailed);return $d;}
}
